### ISSUE TITLE
Location names and addresses

### ISSUE THREAD

**Issue by diaholliday** [City-Bureau/documenters-aggregator#197]
Can we split the "location name" tab into 2 separate tabs? One for Location names, i.e. Council Names, Shepherd Church, etc and one for the street address.

**Comment by r-wei** [comment]
This is somewhat complicated from a coding perspective because the location names and street addresses are quite varied, and there aren't simple rules you could give a machine for determining where the location name ends and where the street address starts. 

For some of the spiders, it is doable, for example, if the location is the same for all of the events. But for others, you would need something smarter like machine learning. For that, I think we can use this [Parserator API](https://parserator.datamade.us/usaddress) made by DataMade. The idea is the same as with Mapzen--we scrape the information from the website, and then pass it to a 3rd party which parses location into name and street address for us. The catch is that you can only make 1,000 free requests to the Parserator. Here is their [pricing scheme](https://parserator.datamade.us/api-docs#pricing).

We can cache results from the Parserator, so we only have to make a request once. I'll take a look through the spider and get an estimate for how many requests we would need to make.

**Comment by diaholliday** [comment]
Ah I see, thanks makes sense, thanks for explaining the coding end of things. With that in mind, this issue is less of a priority on my end. The way it works now perfectly fine. Splitting it into two columns would be ideal but not necessary, and it sounds like the work involved may not be worthwhile at this stage. 

If you can take a look and get an estimate on the requests that should be good for now. We can reassess if it becomes an issue but I don't expect it to.

**Comment by diaholliday** [comment]
@r-wei it looks like some (not many) of the entries do have it split up in airtable. Not sure why that is. we may need to merge those into the location_name columns instead?

![screen shot 2017-12-01 at 6 05 18 pm](https://user-images.githubusercontent.com/4017450/33508825-751d9410-d6c2-11e7-82bb-f55845c5a54b.png)

**Comment by r-wei** [comment]
That's happening because some of our contributors were ambitious and built the splitting into their spiders :) I found out that mapzen api may be able to do the splitting as well. Stay tuned for how it goes..
