### ISSUE TITLE
Leverage OCD/Datamade scrapers and projects

### ISSUE THREAD

**Issue by jim** [City-Bureau/documenters-aggregator#74]
This has come up a few times in various issues (#33, #5). We should evaluate the following existing projects and APIs and identify how we can leverage them to eliminate duplicated effort:

1. Open Civic Data has some scrapers already built that we should consider using:
    * [python-legistar-scraper](https://github.com/opencivicdata/python-legistar-scraper)
    * [opencivicdata/scrapers-us-municipal](https://github.com/opencivicdata/scrapers-us-municipal/blob/master/chicago/events.py)

2. [Datamade has an API](http://ocd-api-documentation.readthedocs.io/en/latest/) that is used to power [Councilmatic](https://chicago.councilmatic.org/events/), which displays Chicago City Council meetings.

**Comment by r-wei** [comment]
It looks like the scrapers that have already been built are for the [Chicago Clerk's Office](https://chicago.legistar.com/Calendar.aspx). 
- DataMade has an [api for the data](http://ocd-api-documentation.readthedocs.io/en/latest/), and Bonnie is looking into using scrapy on it.
- Open Civic Data has put up the [code](https://github.com/opencivicdata/scrapers-us-municipal/blob/master/chicago/events.py) for a legistar scraper. It looks like OCD's [python-legistar-scraper package](https://github.com/opencivicdata/python-legistar-scraper) is built using OCD's [pupa package](https://github.com/opencivicdata/pupa), which is built using scrapelib. I'm not sure if OCD's python-legistar-scraper inherits from scrapy anywhere along the way...

The other two sites we have on legistar are the park district board of commissioners (Dan has been working on this) and cook county board of commissioners. Not sure if there are more sites we would want to add? Forest mentioned the forest preserve and metropolitan water reclamation district.

I can take a crack at scraping the cook county board of commissioners with OCD's python-legistar-scraper instead of scrapy. If there are no other legistar sites we want, then we'd be done. If there are, I can be a resource on Tuesdays for those who want to try out OCD's package.

**Comment by eads** [comment]
re that API -- we could use scrapy as a glorified copying mechanism

re: the legistar thing; I didn't quite realize so many local events were using legistar. I thought about pupa for this but I like scrapy better for a lot of reasons (it's just more robust as far as I can tell). Perhaps there's a way to steal the existing parsing logic from pupa and again use scrapy as a glorified copying machine that essentially just handles request dispatch.

**Comment by r-wei** [comment]
OCD's python-legistrar-scraper is structured differently from our project. It's organized by geography. To run an OCD scraper, you have to download their repo and call something like `pupa upgrade chicago`. It's not straightforward (to me) how to combine the code from both repos.

This is what I think we should do for legistar sites:
- Access the data using the [legistar api](http://webapi.legistar.com/) -- **need the name of the client**
- Parse using scrapy: the logic from OCD's [LegistarAPIScraper class](https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/base.py) or [ChicagoEventsScraper](https://github.com/opencivicdata/scrapers-us-municipal/blob/master/chicago/events.py) could be helpful for parsing the data

Summary / status of our 3 legistar sites:
- Chicago Clerk's office: Bonnie is using scrapy on DataMade's data api
- Cook County Forest Preserve: Ben has a [WIP spider](https://github.com/City-Bureau/documenters-aggregator/pull/42)
- Cook County Board of Commissioners: I'll keep working on this. Unfortunately, I haven't been able to guess the name of the client for the legistar api

**Comment by eads** [comment]
If we do wind up copying some of that logic directly, we'll need to update the license e.g. https://github.com/City-Bureau/documenters-aggregator/blob/master/LICENSE#L26-L54 -- not a big deal, just want to note it for posterity.

**Comment by fgregg** [comment]
the python-legistar-scraper does *not* have pupa as a dependency. We use it for our pupa scrapers, but you can use it without using pupa. Trust me when I say that we are handling a *lot* of complexity for you in in python-legistar-scraper.

**Comment by r-wei** [comment]
@fgregg, I would be happy to use python-legistar-scraper and not have to re-write code. 

Trying to understand how to use it... I think we'd be interested in the LegistarScraper class in [base.py](https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/base.py) or LegistarEventsScraper class in [events.py](https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/events.py). However, both of these inherit from pupa.scrape.Scraper... What am I missing? Is there an example of using a non-pupa scraper?

**Comment by fgregg** [comment]
@r-wei you are right, sorry about that. There is no substantive dependency on pupa though. If you do want to use it, you can remove the dependency and replace it with `scrapelib.Scraper` If you can down that route, we'll work with you to get that change brought into `master` and remove the `pupa dependency`

**Comment by r-wei** [comment]
Thanks @fgregg , I opened an [issue](https://github.com/opencivicdata/python-legistar-scraper/issues/44) with some code that works without pupa. 

@eads, @bonfirefan, for scraping the cook county board of commissioners legistar site, I think David was originally right that we an use OCD's LegistarEventsScraper (example [here](https://github.com/opencivicdata/python-legistar-scraper/issues/44)), and use a scrapy spider to copy the info.

**Comment by r-wei** [comment]
legistar spiders are done
